"""add_patient_email_to_cases

Revision ID: 076dafcd3070
Revises: fe644d4865c3
Create Date: 2026-04-12 02:09:02.797615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076dafcd3070'
down_revision: Union[str, Sequence[str], None] = 'fe644d4865c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_cases', sa.Column('patient_email', sa.String(length=254), nullable=True))
    op.create_index(op.f('ix_patient_cases_patient_email'), 'patient_cases', ['patient_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_cases_patient_email'), table_name='patient_cases')
    op.drop_column('patient_cases', 'patient_email')
    # ### end Alembic commands ###
